CREATE DATABASE IF NOT EXISTS NordicDoor;
USE NordicDoor;

CREATE TABLE IF NOT EXISTS Bruker(
  AnsattNr INTEGER NOT NULL,
  Fornavn VARCHAR(50) NOT NULL,
  Etternavn VARCHAR(50) NOT NULL,
  Email VARCHAR(150) NOT NULL,
  PassordHash VARCHAR(200) NOT NULL,
  Opprettet DATETIME NOT NULL,
  Rolle VARCHAR(50),
  LederId INTEGER DEFAULT NULL,
  KEY LederId (LederId),
  FOREIGN KEY (LederId) REFERENCES Bruker(AnsattNr),
  CONSTRAINT PK_Bruker PRIMARY KEY(AnsattNr)
);

CREATE TABLE IF NOT EXISTS Team(
  TeamId INTEGER NOT NULL AUTO_INCREMENT,
  Navn VARCHAR(50),
  AvdelingsId INTEGER,
  CONSTRAINT PK_Team PRIMARY KEY (TeamId)
);

CREATE TABLE IF NOT EXISTS Forslag(
  ForslagsId INTEGER NOT NULL AUTO_INCREMENT,
  ForfatterId INTEGER NOT NULL,
  TeamId INTEGER NOT NULL,
  Emne VARCHAR(150) NOT NULL,
  Beskrivelse VARCHAR(2000) NOT NULL,
  Bilde MEDIUMBLOB,
  Status VARCHAR(5) DEFAULT "plan" NOT NULL,
  Opprettet DATETIME,
  SistOppdatert DATETIME,
  Frist DATETIME,
  Kategori VARCHAR(150),
  CONSTRAINT PK_Forslag PRIMARY KEY (ForslagsId),
  FOREIGN KEY (ForfatterId) REFERENCES Bruker(AnsattNr),
  FOREIGN KEY (TeamId) REFERENCES Team(TeamId)
);

CREATE TABLE IF NOT EXISTS TeamMedlemskap(
  TeamId INTEGER,
  AnsattNr INTEGER,
  CONSTRAINT PK_TeamMedlemskap PRIMARY KEY (TeamId, AnsattNr),
  FOREIGN KEY (TeamId) REFERENCES Team(TeamId),
  FOREIGN KEY (AnsattNr) REFERENCES Bruker(AnsattNr)
);

CREATE TABLE IF NOT EXISTS Rolle(
  RolleId INTEGER NOT NULL,
  RolleNavn VARCHAR(150),
  CONSTRAINT PK_Rolle PRIMARY KEY (RolleId)
);

CREATE TABLE IF NOT EXISTS BrukerRolle(
  AnsattNr INTEGER NOT NULL,
  RolleId INTEGER NOT NULL,
  CONSTRAINT PK_BrukerRolle PRIMARY KEY (AnsattNr, RolleId),
  CONSTRAINT FK_BrukerRolle_Rolle FOREIGN KEY (RolleId) REFERENCES Rolle(RolleId) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_BrukerRolle_Bruker FOREIGN KEY (AnsattNr) REFERENCES Bruker(AnsattNr) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ForslagKobling(
  AnsattNr INTEGER NOT NULL,
  ForslagsId INTEGER NOT NULL,
  CONSTRAINT PK_ForslagKobling PRIMARY KEY (AnsattNr, ForslagsId),
  CONSTRAINT FK_ForslagKobling_Bruker FOREIGN KEY (AnsattNr) REFERENCES Bruker(AnsattNr) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ForslagsId) REFERENCES Forslag(ForslagsId) ON DELETE CASCADE ON UPDATE CASCADE
);
