CREATE DATABASE IF NOT EXISTS nordicdoor;
USE nordicdoor;

CREATE TABLE IF NOT EXISTS Bruker(
  BrukerId INTEGER NOT NULL,
  ForNavn VARCHAR(50) NOT NULL,
  EtterNavn VARCHAR(50) NOT NULL,
  Email VARCHAR(150) NOT NULL,
  PassordHash VARCHAR(200) NOT NULL,
  Opprettet DATETIME NOT NULL,
  Rolle VARCHAR(50),
  SjefsId INTEGER,
  FOREIGN KEY (SjefsId) REFERENCES Bruker(BrukerId),
  CONSTRAINT PK_Bruker PRIMARY KEY(BrukerId) 
);

CREATE TABLE IF NOT EXISTS Team(
  TeamId INTEGER NOT NULL AUTO_INCREMENT,
  Navn VARCHAR(50),
  AvdelingsId INTEGER,
  CONSTRAINT PK_Team PRIMARY KEY (TeamId)
);

CREATE TABLE IF NOT EXISTS Forslag(
  ForslagsId INTEGER NOT NULL AUTO_INCREMENT,
  ForfatterId INTEGER NOT NULL,
  TeamId INTEGER NOT NULL,
  Emne VARCHAR(150) NOT NULL,
  Beskrivelse VARCHAR(2000) NOT NULL,
  Bilde MEDIUMBLOB,
  Status INTEGER DEFAULT 1 NOT NULL,
  Opprettet DATETIME,
  SistOppdatert DATETIME,
  Frist DATETIME,
  Kategori VARCHAR(150),
  CONSTRAINT PK_Forslag PRIMARY KEY (ForslagsId),
  CONSTRAINT FK_Forslag_Bruker FOREIGN KEY (ForfatterId) REFERENCES Bruker(BrukerId) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Forslag_Team FOREIGN KEY (TeamId) REFERENCES Team(TeamId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TeamMedlemskap(
  TeamId INTEGER,
  BrukerId INTEGER,
  CONSTRAINT PK_TeamMedlemskap PRIMARY KEY (TeamId, BrukerId),
  FOREIGN KEY (TeamId) REFERENCES Team(TeamId),
  CONSTRAINT FK_TeamMedlemskap_Bruker FOREIGN KEY (BrukerId) REFERENCES Bruker(BrukerId)
);

CREATE TABLE IF NOT EXISTS Rolle(
  RolleId INTEGER NOT NULL,
  RolleNavn VARCHAR(150),
  CONSTRAINT PK_Rolle PRIMARY KEY (RolleId)
);

CREATE TABLE IF NOT EXISTS BrukerRolle(
  BrukerId INTEGER NOT NULL,
  RolleId INTEGER NOT NULL,
  CONSTRAINT PK_BrukerRolle PRIMARY KEY (BrukerId, RolleId),
  CONSTRAINT FK_BrukerRolle_Rolle FOREIGN KEY (RolleId) REFERENCES Rolle(RolleId) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_BrukerRolle_Bruker FOREIGN KEY (BrukerId) REFERENCES Bruker(BrukerId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ForslagKobling(
  BrukerId INTEGER NOT NULL,
  ForslagsId INTEGER NOT NULL,
  CONSTRAINT PK_ForslagKobling PRIMARY KEY (BrukerId, ForslagsId),
  CONSTRAINT FK_ForslagKobling_Bruker FOREIGN KEY (BrukerId) REFERENCES Bruker(BrukerId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ForslagsId) REFERENCES Forslag(ForslagsId) ON DELETE CASCADE ON UPDATE CASCADE
);
